version : '3'
services:
    couchpotato:
        image: "couchpotato/couchpotato"
        container_name: "couchpotato"
        volumes:
            - "./couchpotato/config:/datadir"
            - "./kodi/Movies:/media"
        ports:
            - "5050:5050"
        restart: unless-stopped
    pymedusa:
        image: linuxserver/medusa
        container_name: "medusa"
        environment: 
            - PGID=1001
            - PUID=1001
            - TZ=Europe/Paris
        volumes: 
            - "./medusa/config:/config"
            - "./transmission/completed:/downloads"
            - "./kodi/TV Shows:/tv"
        ports:
            - "8081:8081"
        restart: unless-stopped
    transmission:
        image: linuxserver/transmission
        container_name: "transmission"
        volumes:
            - "./transmission/config:/config"
            - "./transmission/completed:/downloads"
            - "./transmission/incomplete:/watch"
        ports:
            - "9091:9091"
            - "51413:51413/udp"
            - "51413:51413"
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Europe/Paris
        