version : '3'
services:
    couchpotato:
        image: "linuxserver/couchpotato"
        container_name: "couchpotato"
        volumes:
            - "./couchpotato/config:/config"
            - "./kodi/Movies:/movies"
            - "./transmission/downloads:/downloads"
        ports:
            - "5050:5050"
        networks:
            - local
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Europe/Paris
        restart: unless-stopped
    pymedusa:
        image: linuxserver/medusa
        container_name: "medusa"
        networks:
            - local
        environment: 
            - PGID=1001
            - PUID=1001
            - TZ=Europe/Paris
        volumes: 
            - "./medusa/config:/config"
            - "./transmission/downloads:/downloads"
            - "./kodi/TV Shows:/tv"
        ports:
            - "8081:8081"
        restart: unless-stopped
    transmission:
        image: linuxserver/transmission
        container_name: "transmission"
        networks:
            - local
        restart: unless-stopped
        volumes:
            - "./transmission/config:/config"
            - "./transmission/downloads:/downloads"
            - "./transmission/watch:/watch"
        ports:
            - "9091:9091"
            - "51413:51413/udp"
            - "51413:51413"
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Europe/Paris
networks:
    local:
